import type { Metadata } from "next";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NextThemesProvider defaultTheme="light">
          <div className="max-w-6xl mx-auto relative">
            <Navbar />
            {children}
          </div>
        </NextThemesProvider>
      </body>
    </html>
  );
}
